import type { Locale } from "./i18n";

const rows = {
  "zh-Hant": [
    "同步中，請稍候",
    "本輪同步完成",
    "目前沒有需要傳輸的變更",
    "部分資料需要處理",
    "未完成，請查看原因",
    "尚無可同步的本機對話",
    "已暫停",
    "等待同步",
    "已上傳同步包",
    "已下載同步包",
    "已加入本機的對話／記憶",
    "技術詳細資訊",
    "本機保存時間",
    "時間未知",
    "同步包",
    "展開全部",
    "收合全部",
    "同步結果",
    "已有不同版本；原資料已保留，可將快照恢復到新資料夾。",
    "Agent 正在寫入資料；稍後再同步。",
    "資料超過目前容量限制；請檢查來源大小與程式版本。",
    "找不到來源；請檢查 Agent 資料路徑。",
    "無法讀取此格式；請確認 Agent 與程式版本。",
    "請解鎖系統憑證庫，並允許 Bastet 存取。",
    "連線未完成；請檢查網路與 Google 授權後重試。",
    "找不到 Agent Memory OS CLI；請指定執行檔。",
    "此項目未完成；請查看詳細資訊後重試。",
    "本輪傳輸",
    "同步包時間代表保存到這台電腦的時間，不是原始對話建立時間。",
    "排隊中，等待可用同步位置",
  ],
  "zh-Hans": [
    "正在同步，请稍候",
    "本轮同步完成",
    "目前没有需要传输的变更",
    "部分数据需要处理",
    "未完成，请查看原因",
    "暂无可同步的本地对话",
    "已暂停",
    "等待同步",
    "已上传同步包",
    "已下载同步包",
    "已加入本地的对话／记忆",
    "技术详细信息",
    "本地保存时间",
    "时间未知",
    "同步包",
    "全部展开",
    "全部收起",
    "同步结果",
    "已有不同版本；原数据已保留，可将快照恢复到新文件夹。",
    "Agent 正在写入数据；稍后再同步。",
    "数据超过当前容量限制；请检查来源大小与程序版本。",
    "找不到来源；请检查 Agent 数据路径。",
    "无法读取此格式；请确认 Agent 与程序版本。",
    "请解锁系统凭据库，并允许 Bastet 访问。",
    "连接未完成；请检查网络与 Google 授权后重试。",
    "找不到 Agent Memory OS CLI；请指定可执行文件。",
    "此项目未完成；请查看详细信息后重试。",
    "本轮传输",
    "同步包时间表示保存到此电脑的时间，不是原始对话创建时间。",
    "排队中，等待可用同步位置",
  ],
  en: [
    "Syncing, please wait",
    "This cycle is complete",
    "No changes needed transfer",
    "Some items need attention",
    "Not completed — check the reason",
    "No local conversations to sync",
    "Paused",
    "Waiting to sync",
    "Bundles uploaded",
    "Bundles downloaded",
    "Conversations / memories added locally",
    "Technical details",
    "Saved on this computer",
    "Time unavailable",
    "snapshots",
    "Expand all",
    "Collapse all",
    "Sync results",
    "A different version already exists. Your original is preserved; restore the snapshot to a new folder.",
    "The agent is writing data. Try syncing again shortly.",
    "Data exceeds the current limit. Check source size and app version.",
    "Source not found. Check the agent data path.",
    "This format could not be read. Check agent and app versions.",
    "Unlock the system credential store and allow Bastet access.",
    "Connection did not complete. Check your network and Google authorization, then retry.",
    "Agent Memory OS CLI was not found. Select its executable.",
    "This item did not complete. Check technical details and retry.",
    "This cycle",
    "Snapshot times indicate when they were saved on this computer, not when the original conversation began.",
    "Queued; waiting for a sync slot",
  ],
  ja: [
    "同期中です",
    "今回の同期が完了しました",
    "転送が必要な変更はありません",
    "一部の項目に対応が必要です",
    "未完了：原因を確認してください",
    "同期できるローカル会話はありません",
    "一時停止中",
    "同期待ち",
    "送信したバンドル",
    "受信したバンドル",
    "ローカルに追加した会話・記憶",
    "技術情報",
    "この端末への保存日時",
    "日時不明",
    "スナップショット",
    "すべて展開",
    "すべて折りたたむ",
    "同期結果",
    "異なる版が存在します。元のデータは保持されています。新規フォルダーに復元できます。",
    "Agent が書き込み中です。しばらくして再試行してください。",
    "データが上限を超えています。サイズとアプリの版を確認してください。",
    "ソースが見つかりません。データのパスを確認してください。",
    "形式を読み取れません。Agent とアプリの版を確認してください。",
    "認証情報ストアを解除し、Bastet のアクセスを許可してください。",
    "接続が完了しませんでした。ネットワークと Google 認証を確認してください。",
    "Agent Memory OS CLI の実行ファイルを選択してください。",
    "未完了の項目です。技術情報を確認して再試行してください。",
    "今回の転送",
    "日時はこの端末への保存日時であり、元の会話の開始日時ではありません。",
    "順番待ち・同期枠の空きを待機中",
  ],
  ko: [
    "동기화 중입니다",
    "이번 동기화 완료",
    "전송할 변경 사항이 없습니다",
    "일부 항목을 확인하세요",
    "미완료: 원인을 확인하세요",
    "동기화할 로컬 대화가 없습니다",
    "일시 중지됨",
    "동기화 대기",
    "업로드한 묶음",
    "다운로드한 묶음",
    "로컬에 추가한 대화 / 기억",
    "기술 상세 정보",
    "이 컴퓨터에 저장한 시간",
    "시간 정보 없음",
    "스냅샷",
    "모두 펼치기",
    "모두 접기",
    "동기화 결과",
    "다른 버전이 있습니다. 원본은 유지되며 새 폴더로 복원할 수 있습니다.",
    "Agent가 데이터를 쓰는 중입니다. 잠시 후 다시 시도하세요.",
    "데이터가 용량 제한을 초과합니다. 크기와 앱 버전을 확인하세요.",
    "소스가 없습니다. Agent 데이터 경로를 확인하세요.",
    "형식을 읽을 수 없습니다. Agent와 앱 버전을 확인하세요.",
    "자격 증명 저장소를 잠금 해제하고 Bastet 접근을 허용하세요.",
    "연결이 완료되지 않았습니다. 네트워크와 Google 승인을 확인하세요.",
    "Agent Memory OS CLI 실행 파일을 선택하세요.",
    "완료되지 않았습니다. 상세 정보를 확인하고 재시도하세요.",
    "이번 전송",
    "시간은 이 컴퓨터에 저장한 시간이며 원래 대화 시작 시간이 아닙니다.",
    "대기 중 · 동기화 작업 자리 대기",
  ],
} as const;
export const syncDisplay = rows;
export function issueText(code: string, locale: Locale) {
  const t = rows[locale];
  if (code === "session_conflict") return t[18];
  if (code === "source_changing") return t[19];
  if (/limit/.test(code)) return t[20];
  if (code === "source_missing") return t[21];
  if (/session_invalid|session_format/.test(code)) return t[22];
  if (/credential/.test(code)) return t[23];
  if (/network|drive_|oauth|reauth/.test(code)) return t[24];
  if (code === "memory_cli_missing") return t[25];
  return t[26];
}
export function savedTime(seconds: number | null | undefined, locale: Locale) {
  if (seconds == null || !Number.isFinite(seconds) || seconds < 0)
    return rows[locale][13];
  const date = new Date(seconds * 1000);
  return Number.isNaN(date.getTime())
    ? rows[locale][13]
    : date.toLocaleString(locale, { dateStyle: "medium", timeStyle: "medium" });
}
